### ISSUE TITLE
Lacking genericity

### ISSUE THREAD

**Issue by AmiralBl3ndic** [meilisearch/meilisearch-java#12]
The wrapper lacks genericity a lot: for the moment each data it returns is a string and must be parsed by the program using the wrapper.
We should implement generic methods allowing to retrieve dynamically mapped types rather than simply strings.

**Comment by AmiralBl3ndic** [comment]
I have started working on some of these methods, this will be the object of ny next PR

**Comment by eskombro** [comment]
This has already been achieved by several PRs. From my POV the only important missing part of this should be aolved by #68 
I'm therefore closingthis issue. Feel free to reopen it or to comment on it if that is not the case!
