### ISSUE TITLE
Add documentation on Search

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-java#128]
Inspired on our [PHP SDK's search wiki](https://github.com/meilisearch/meilisearch-php/wiki/Search), this document can specify features about search as the different methods exposed to the user (`search()` and `rawSearch()`, different constructors for this methods etc...

The repo's README can have a link to this WIKI in the `Custom Search` section as in this [PHP README example](https://github.com/meilisearch/meilisearch-php/blob/main/README.md#custom-search-)

**Comment by curquiza** [comment]
I agree with this idea, however I would rather not a Wiki. After using wiki, we found out this is not as easy to maintain as a "classic" file (like a README) in our repository: it's impossible to create PRs.
So, ok for this idea, but in the README 🙂

**Comment by trangntt-016** [comment]
Hi @eskombro 
Could you please assign this issue to me?

**Comment by alallema** [comment]
Hi @trangntt-016,
Thanks for asking. It's done

**Comment by trangntt-016** [comment]
@eskombro , @alallema 
Should I insert my documentation to the README's Custom Search or create another .md and link it to the README's search section?

**Comment by alallema** [comment]
This problem was written before the sample code was available. Now that it is, this issue is no longer required and would require too much maintenance to keep. I'm really sorry but I'll have to close this issue to maybe rewrite it and close your PR too. Even if your PR is really great.
