### ISSUE TITLE
Change the trigger in the publish workflow

### ISSUE THREAD

**Issue by nicolasvienot** [meilisearch/meilisearch-java#141]
Currently, the trigger for the publish workflow is based on the name of the tag on push.
We want to trigger the workflow on release, irrespective of the tag.

⚠️ Should be done by a MeiliSearch team member.

**Comment by curquiza** [comment]
Should apply to all integration repositories then

**Comment by nicolasvienot** [comment]
> Should be applied to all integration repositories then

You're totally right. I talked with @eskombro about it and we agreed that we would not do it for now.

The main reason is that the `on release` trigger is not that obvious and will not trigger if the release is automatically done by a github action for example. That's not the case now, but might be something that the integration team wants to take in consideration before applying to all repositories.

I might create an issue in the integration-guides to keep that in mind.
