### ISSUE TITLE
Test placeholder search

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-java#15]
Placeholder search lets the user send a null `query` parameter in order to apply all the ranking rules to the documents in the index without matching them with a specific query, and return the results to the user. It is different to sending an empty string as a query, in which case you won't receive any results. This behavior should be explicitly tested in the SDK.

More info about Placeholder search [here](https://docs.meilisearch.com/guides/main_concepts/search.html#placeholder-search) 

________________________________
UPDATE: 

Placeholder works 👍

Placeholder Search can be used by:
- Using a null query: `q=null`
- Using an empty String: `q=""`

Tests are still missing (both options, null and empty String, should be tested).

**Comment by eskombro** [comment]
This behavior is going to change soon, as described in [this PR](https://github.com/meilisearch/MeiliSearch/pull/916). An empty query will be handled as a Placeholder search, so sending an empty string or null as a query will result in getting placeholder results

**Comment by curquiza** [comment]
Placeholder works 👍  
But tests are still missing.

**Comment by luis-valdez** [comment]
Hello again guys!
Is this issue still relevant and available? If so I would like to work on it :).

**Comment by eskombro** [comment]
Absolutely @luis-valdez !

Only adding tests is needed!

**Comment by curquiza** [comment]
Oh, I just realize the issue description is outdated!!
Unlike the description says:
A placeholder can be used with:
- `q=null` 
- `q=""` (an empty string)
=> **whatever the choice, the result will be the same**

Tests with both should be added.

@eskombro can you update the issue description please?

And thanks @luis-valdez for your huge involvement 💪

**Comment by eskombro** [comment]
@curquiza @luis-valdez  description updated

**Comment by luis-valdez** [comment]
Awesome. Thank you guys for letting me contribute :D!

**Comment by eskombro** [comment]
> Awesome. Thank you guys for letting me contribute :D!

Oh, we are more than happy to have your help! Thanks a lot for everything you are doing 🎉
