### ISSUE TITLE
Why we have 2 http client dependency?

### ISSUE THREAD

**Issue by ppshobi** [meilisearch/meilisearch-java#188]
Hi, I am super new to java, So I am wondering why we have 2 http client dependencies? 

https://github.com/meilisearch/meilisearch-java/blob/2713a446c3198b2aab22bf3f9df64b1769197ec7/build.gradle#L41-L43

**Comment by alallema** [comment]
Hi @ppshobi,
It comes from this [PR](https://github.com/meilisearch/meilisearch-java/pull/34).
I'm not sure of the why, I think the goal was to allow the user to create a custom HTTP client.
Maybe @eskombro could answer better.

**Comment by ppshobi** [comment]
I think I got why multiple dependencies are listed, but whenever I try to build the project I am getting errors like following

> /Project/meilisearch-java/src/test/java/com/meilisearch/sdk/http/CustomOkHttpClientTest.java:19: error: package okhttp3 does not exist
> import okhttp3.*;

or 

>/Project/meilisearch-java/src/test/java/com/meilisearch/integration/DocumentsTest.java:14: error: package org.jetbrains.annotations does not exist

is there a command where I can Install all the dependencies?

**Comment by alallema** [comment]
Normally `./gradlew build` should install all the dependencies.
But you can try:
```
./gradlew build --refresh-dependencies
```

**Comment by ppshobi** [comment]
@alallema Thanks closing this issue
