### ISSUE TITLE
Choose a linter and integrate it to CI and docs

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-java#19]
- [ ] Choose a well maintained and known Linter for Java
- [ ] Run the linter for the whole SDK code and make a Pull Request
- [ ] Add a task in the CI [GitHub Actions] that runs automatically the linter (Lint will be required for any merge/contribution afterwards)

Do not hesitate to contact us if you have any doubts or questions!

**Comment by AmiralBl3ndic** [comment]
I started looking for a linter and [`error-prone`](https://errorprone.info/index) seems to be a good solution.
There is no official gradle plugin for it though, we will have to rely upon [the community-developed plugin](https://github.com/tbroyer/gradle-errorprone-plugin)

**Comment by eskombro** [comment]
It seems interesting. A pity that it doesn't have a code formatting tool. The plugin seems good.

What do you think if we use https://github.com/google/google-java-format?

**Comment by AmiralBl3ndic** [comment]
@eskombro I heard some friends talking about using [`prettier-java`](https://github.com/jhipster/prettier-java) for code formatting. I haven't personally tried it, but it seems like a good option to achieve code formatting in Java. Just be advised they also told me that it requires a bit configuration and this relies on each user having a node environment setup to use with `npm` or `yarn`.

**Comment by eskombro** [comment]
Sorry for the late answer @AmiralBl3ndic, and thanks for the suggestion!

I changed team at MeiliSearch, and probably @alallema will be addressing this topic and issue when she gets some time :)

Thanks for all your help, again 🎉

**Comment by ppshobi** [comment]
We could close this issue as #187 is merged, and we are using spotless, which is a no dependency linter. Also a CI step has been added
