### ISSUE TITLE
Make filter work also with the array syntax

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-java#197]
**Description**
In v0.21.0, the with_filter function corresponding to the filter search parameter can accept both array and string syntax:
```
string:  "filter": "genre = comedy AND price > 13" 
array:  "filter": ["genre = comedy", "price > 13"] 
```
Currently, only the string syntax is accepted in SDK Java:
```
public class SearchRequest {
    private String filter;
    ...
```
```
SearchRequest searchRequest =
       new SearchRequest("and").setFilter("title = \"The Dark Knight\" OR id = 290859");
SearchResult searchResult = index.search(searchRequest);
```
`Getter`  and `Setter` for `filter` should accept both syntaxes or another param should be created.
tests must be added

**Comment by vishnugt** [comment]
This looks interesting, can I give this a try?

From the documentation I can see that the filters can take arrays with nesting up to 2 levels, so ideally we would want to support all the cases right?
That means the following three cases:
- String (already supported)
- String[] (need to add support, mentioned in the issue description)
- String[][] (what about this case? I'm assuming we need to support this as well)

@alallema @curquiza

**Comment by alallema** [comment]
Hi @vishnugt!
Of course, you can. And Yes for the three cases, but you can also just add the `String[]` case in the first instance if you prefer.
Thank a lot

**Comment by vishnugt** [comment]
@alallema I've raised a PR for this, please have a look at it, at your convenience!
