### ISSUE TITLE
java-sdk  bug?

### ISSUE THREAD

**Issue by asdshuaishuai** [meilisearch/meilisearch-java#211]
![image](https://user-images.githubusercontent.com/72966668/133575119-ab5bf7c5-95bb-40a1-9f55-ed8c767d4c0e.png)

**Comment by alallema** [comment]
Hi @asdshuaishuai,
Which version of MeiliSearch did you use? The sort field is available from v0.22.0 of Meilisearch.
Thanks

**Comment by asdshuaishuai** [comment]
thinks ,I used v0.22
I talked about this question with your customer service, and I will set up sortableamtributes (), but still report an error.
![image](https://user-images.githubusercontent.com/72966668/133582280-f17b41e5-0023-4eb8-864d-8689bbcd50d1.png)
I don't know if I am using the problem, this is my code.
![image](https://user-images.githubusercontent.com/72966668/133582456-02bda170-bb35-464f-967f-1dd472036d58.png)

**Comment by alallema** [comment]
Hi @asdshuaishuai,
Thanks for your reply can you try:
`curl http://127.0.0.1:7700/version` and tell me the exact return you have?
Thanks

**Comment by asdshuaishuai** [comment]
The server is used by V0.22. It is 0.21 for the test server. I am sorry, I am wrong.

**Comment by alallema** [comment]
> The server is used by V0.22. It is 0.21 for the test server. I am sorry, I am wrong.
> 
> 

No problem 😉
