### ISSUE TITLE
Add GetOrCreateIndex method

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-java#22]
Gets the index instance or creates a new one if it does not exist

- [ ] Implement `getOrCreate` method
- [ ] Add tests

Follows [this discussion](https://github.com/meilisearch/integration-guides/issues/2)

**Comment by arjunrc143** [comment]
@eskombro Can I give a try on this?

**Comment by eskombro** [comment]
Hello @arjunrc143 

I am very sorry for my late answer!
Indeed, it would be great!

**Comment by arjunrc143** [comment]
> Hello @arjunrc143
> 
> I am very sorry for my late answer!
> Indeed, it would be great!
> 
> Do not hesitate if you need help with anything

Does the master contains breaking changes?

**Comment by arjunrc143** [comment]
https://github.com/meilisearch/meilisearch-java/pull/45

I have added a PR. Please check. I havent updated the integration tests, but I would like to. Can you please help me in setting up environment for integration tests. @eskombro

**Comment by eskombro** [comment]
> Does the master contains breaking changes?

This SDK is still in WIP, so breaking changes are more than common. When we do the release, it will follow the semver system to announce braking changes! But for now, there is no point in trying to be stable :)

**Comment by eskombro** [comment]
> #45
> 
> I have added a PR. Please check. I havent updated the integration tests, but I would like to. Can you please help me in setting up environment for integration tests. @eskombro

Are you in [our Slack](https://slack.meilisearch.com/)? Do not hesitate to contact me there (I'm Samuel) and I will be happy to help you!

We will add some guides soon to this repo, but it is still a bit early to add guides, as everything changes all the time
