### ISSUE TITLE
Method to get all the indexes should return a list of instance

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-java#230]
Currently, the `get_all_indexes` method returns a raw list of object, but not a list of `Index` instance. This is the only index-related method that does not return an `Index` instance.

An instance is more convenient to manipulate than a raw object. See this [example](https://github.com/meilisearch/meilisearch-python/issues/258#issuecomment-835866135).

TODO

- [ ] Change the return of the current `get_all_indexes`: make it return a list of `Index` instances
- [ ] Provide `get_all_raw_indexes`: a method that returns the list of object of indexes, so the response of the MeiliSearch server.
- [ ] Add tests

⚠️ No code duplication: use `get_all_raw_indexes` in `get_all_indexes`.

Related to https://github.com/meilisearch/integration-guides/issues/122

⚠️ Also, this issue is generated, and `get_all_indexes` might be named differently in this package. Keep the already existing way of naming in this package to stay idomatic with the language and the repository.

Sorry if this is already partially/completely implemented, feel free to let me know about the state of this issue.

**Comment by shivamchourasia4** [comment]
Hey there @curquiza , I would like to work on this.
You can assign it to me.

**Comment by shivamchourasia4** [comment]
The get_all_indexes method is already implemented as desired.
I am just a beginner, so I won't be able to contribute.

**Comment by shivani1120** [comment]
I would like to work on this issue. Could u assign me?

**Comment by alallema** [comment]
Yes of course. You are assigned! :)

**Comment by curquiza** [comment]
Hello @ezienecker! you're completely right, my bad!
I close this issue then! :)
