### ISSUE TITLE
Update .code-samples.meilisearch.yaml with the new sub-settings methods

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-java#269]
**Description**
The following sub-settings methods have just been implemented:
- Synonyms
- Stop-words
- Searchable attributes
- Displayed attributes
- Attributes for faceting
- Distinct attribute
These should be added in the [.code-samples.meilisearch.yam](https://github.com/meilisearch/meilisearch-java/blob/main/.code-samples.meilisearch.yaml)l file at the root of the repository.

All the `reset` sub-settings samples should be added
All the `get` and `update` sub-settings samples should be updated.

For more information about the code sample [see](https://github.com/meilisearch/meilisearch-java/issues/20)

**Comment by irenejoeunpark** [comment]
Hi @alallema , I am trying to add some examples for the sub-setting methods. 
I have some questions for naming of the examples, does it have to be under different example name, or incremental of the existing reset examples?
For example, if I want to add an example for reseting distinct attribute function using updateRankingRuleSettings(null), do I have to use "reset_distinct_attribute_2" or, "reset_distinct_attribute_using_null_1" ?

**Comment by curquiza** [comment]
Hello @irenejoeunpark 
Thanks for your involvement in this project :)
The code-samples correspond to code snippets in the documentation. For example, this [example to get an index](https://docs.meilisearch.com/reference/api/indexes.html#example-2) corresponds to this code samples:
https://github.com/meilisearch/meilisearch-java/blob/6b4453b5ed6f1800d20b3e90d4df824432652bd0/.code-samples.meilisearch.yaml#L6-L7

=> `movies` is used as index name in this code sample and all the other languages use the same name for this code snippet.

For the missing code samples in this file, you have to do the same: follow the current code snippets present in the docs and "translate" them into Java.

You can notice no code snippets are dedicated at the moment to show how to reset the settings using the `null` value. It means you should not add it. When the docs will dedicated a place for this example, we will add it.

Hope this is clearer, feel free to ask any question :)
