### ISSUE TITLE
Test error on `UpdateStatus` class

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-java#286]
The `UpdateStatus` class (MeiliSearch response for an update status) was modified during the last release #282.
It seems that there are no tests to check for error cases in this class.

**Comment by mohitsaxenaknoldus** [comment]
Is this about writing test cases for that class?

**Comment by alallema** [comment]
Hi @mohitsaxenaknoldus,
Thank you for your interest! That's exactly what it is.

**Comment by mohitsaxenaknoldus** [comment]
Ok, I'll do it. You can assign me.

**Comment by alallema** [comment]
Hi @mohitsaxenaknoldus,
We have chosen not to assign people to our issues anymore because sometimes people ask to be assigned and never come back, which discourages real volunteer contributors from opening a PR to fix this problem.
So I remove the assignment but do not hesitate to propose PR they review with pleasure 😊

**Comment by kuruvasatya** [comment]
Hi @alallema 

I wonder if this is a valid issue, as i dont see any UpdateStatus class in the source code, correct me if i am wrong 

Thanks

**Comment by alallema** [comment]
Hi @kuruvasatya,

Thank you for wanting to contribute to this repository :heart:. Unfortunately, this repository is not open to contributions from Hacktoberfest. Indeed it is being reworked and will not participate this year also we prefer to wait until the end of the refactor to accept new PR :blush.

**Comment by joseearias** [comment]
Hi! Is this issue solved. If not I would like to give it a try.

**Comment by alallema** [comment]
Hi @joseearias,
No, not yet. So don't hesitate!

**Comment by alallema** [comment]
Closed because this class doesn't exist anymore
