### ISSUE TITLE
Class Error is not accessible 

### ISSUE THREAD

**Issue by sauterle** [meilisearch/meilisearch-java#292]
**Description**

The UpdateStatus class (MeiliSearch response for an update status) was modified during the last release #282.
In the past, it was possible to check the errors properties: code, type and link. Now it is wrapped in an error class which is package-private.

**Expected behavior**

It is possible to access to the error class to check updates.

**Current behavior**

No access, because class is package-private.

**Environment:**
- MeiliSearch version: v.0.24.0
- meilisearch-java version: v0.6.0

**Comment by alallema** [comment]
Hi @sauterle,
Thanks for raising this issue. You're totally right I didn't think about it when I modify this class during the last release.

**Comment by Artumira96** [comment]
Hello! I've made a PR for this issue, I included some getters for the Error fields and changed the class to public: 
![Screen Shot 2021-12-20 at 21 23 31](https://user-images.githubusercontent.com/80984726/146870743-4f62ce85-720c-44a3-8949-42e1030e2f3c.png)

Please let me know what you think, I'll be aware of this post :) Greetings!
