### ISSUE TITLE
Timeout Exception

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-java#316]
Currently, the Java SDK doesn't use the [`TimeoutException`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/TimeoutException.html).

On most of the SDK there is three main Exception:
- ApiError
- CommunicationError
- TimeoutError

It would be nice to implement a timeout catch everywhere where it would be necessary. 

You can check as an example the Python SDK where the exception is [implemented](https://github.com/meilisearch/meilisearch-python/blob/87278e29b2d2604bc70f802dcbea016aeaa77c4c/meilisearch/errors.py#L46) and [used](https://github.com/meilisearch/meilisearch-python/blob/9e3442635419b14f688abf6f7e54e36d23a8a50c/meilisearch/_httprequests.py#L46).

**Comment by trangntt-016** [comment]
HI @alallema I'm wondering if this issue is still open?

**Comment by alallema** [comment]
HI @trangntt-016,
Thank you for your interest, yes this issue is still open!

**Comment by alallema** [comment]
Closed #438
