### ISSUE TITLE
Workaround for `PATCH` method should be fix

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-java#318]
The `HTTP` `PATCH` method has just been introduced in this SDK following the release of `v0.25.0`. This method is used in the new `updateKey()` method.

**Problem:**
The class [`HttpURLConnection`](https://docs.oracle.com/javase/8/docs/api/java/net/HttpURLConnection.html) doesn't accept the `PATCH` method and the error return is:
```
HttpURLConnection Invalid HTTP method: PATCH
```
There is a Won't Fix bug in OpenJDK for this [here](https://bugs.openjdk.java.net/browse/JDK-7016595). 

**Proposition:**
Meanwhile, I stole a workaround [here](https://github.com/meilisearch/meilisearch-java/blob/ce924295f1f0ec598dc10a4b17c6c4eccaa3a50d/src/main/java/com/meilisearch/sdk/http/DefaultHttpClient.java#L111) in the code to allow to send `PATCH` `HTTP` requests by hacking `HttpURLConnection` methods static field which is used in the checks internally.

But I don't think it is the best way to do it. A better solution should be found if possible.

**Comment by GyrosOfWar** [comment]
If you don't need Java 8 support, you could consider switching to the built-in Java HTTP client instead. (exists since Java 11)

**Comment by alallema** [comment]
Hi @GyrosOfWar,
Thanks for your reply. Indeed I saw that it was supported by Java 11 but I am afraid that there are still too many users who are still on Java 8 to abandon the support.
