### ISSUE TITLE
Adding `details` field to `Task` class

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-java#331]
The Java class `Task` which retrieves the response from `Meilisearch` for a task contains these fields:
```
    protected String status = "";
    protected int uid = 0;
    protected String indexUid = "";
    protected String type = null;
    protected String duration = "";
    protected Date enqueuedAt = null;
    protected Date startedAt = null;
    protected Date finishedAt = null;
    protected TaskError error = null;
```
But the actual response send by `Meilisearch` is like:
```
{
	"uid": 225,
	"indexUid": "WaitForTaskTimoutInMs",
	"status": "succeeded",
	"type": "documentAddition",
	"details": {
		"receivedDocuments": 30,
		"indexedDocuments": 30
	},
	"duration": "PT0.031713875S",
	"enqueuedAt": "2022-01-26T16:54:46.993341418Z",
	"startedAt": "2022-01-26T16:54:46.995596001Z",
	"finishedAt": "2022-01-26T16:54:47.027309876Z"
},
```
It should be more accurate to add a `details` field to the `Task` class to be able to have the entire answer from the `Meilisearch` API.

**Comment by kuruvasatya** [comment]
@alallema  I would love to work on this, please assign this to me

**Comment by alallema** [comment]
Hi @kuruvasatya,
We have chosen not to assign people to our issues anymore because sometimes people ask to be assigned and never come back, which discourages real volunteer contributors from opening a PR to fix this problem.
But I see you already propose an issue, I will review it 😊
Thanks for contributing to Meilisearch ❤️

**Comment by bidoubiwa** [comment]
Hello! The type `details` is not completed. See [example](https://github.com/meilisearch/meilisearch-swift/blob/91825b83431e909cca6a3c0445c15148050846b6/Sources/MeiliSearch/Model/Task.swift#L37) in swift
