### ISSUE TITLE
Add `PATCH` http method and `updateKey()` method

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-java#334]
The `HTTP` `PATCH` method has been introduced in `Meilisearch` following the release of `v0.25.0`. This method is has been used by the new `updateKey()` method.

**Problem:**
The class [`HttpURLConnection`](https://docs.oracle.com/javase/8/docs/api/java/net/HttpURLConnection.html) doesn't accept the `PATCH` method and the error return is:
```
HttpURLConnection Invalid HTTP method: PATCH
```
There is a Won't Fix bug in OpenJDK for this [here](https://bugs.openjdk.java.net/browse/JDK-7016595). 

So a Workaround has been added in this PR #317 explain in this issue #318. But the tests were failing in the Github Actions  with the same error message:
```
java.net.ProtocolException: Invalid HTTP method: PATCH
```
This method has been removed #333 from this SDK but it will be great to find a wait to add the `updateKey()` method.

Some references:
- https://stackoverflow.com/questions/22355235/patch-request-using-jersey-client
- https://reqbin.com/req/java/6psxhnzo/patch-request-example

**Comment by curquiza** [comment]
@gmourier
