### ISSUE TITLE
Implement dumps (add tests and code samples)

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-java#35]
Since [v0.15.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.15.0), MeiliSearch exposes a new functionality: [dumps](https://docs.meilisearch.com/references/dump.html#dumps)

This feature should be implemented in this SDK following [this specificacions](https://github.com/meilisearch/integration-guides/issues/44)

- [ ] Implement dump creation route
- [ ] Implement get dump status route
- [ ] Add tests
- [ ] Add code samples

**Comment by luis-valdez** [comment]
Hello @eskombro @curquiza
If nobody is currently in this issue, I'd love to take it!

**Comment by eskombro** [comment]
Absolutely @luis-valdez, you're on fire 🔥 
Thank you so much! 👍🏽 

Just as a little disclaimer, soon there will be some holidays season for some of us, so if reviews or questions are not done/answered as fast as usual, it's because of this :)

**Comment by luis-valdez** [comment]
I understand @eskombro, enjoy your holidays 🎉
