### ISSUE TITLE
Change getter and setter in `Class` for `@Getter` and `@Setter` from `lombok`

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-java#379]
In some `Class` getter functions are written. It could be better to replace all of them by auto-generated getter/setter from `lombok`.
See example of [`Class` without](https://github.com/meilisearch/meilisearch-java/blob/main/src/main/java/com/meilisearch/sdk/Details.java)
And [`Class` with](https://github.com/meilisearch/meilisearch-java/blob/main/src/main/java/com/meilisearch/sdk/Dump.java)

**Comment by adolfo-trocoli** [comment]
Have you thougth about adding @Data to the hole class? According to the specification, it bundles the features of ToString, EqualsAndHashCode, Getter, Setter and RequiredArgsConstructor. You can also tune it if you don´t want some of these. Let me know if I can help with this or your original proposal of refactoring using @Getter.

**Comment by ghousek1** [comment]
Added class level and field level(depending upon the requirement) @Getter and @Setter for all classes in module.
 pls review the PR https://github.com/meilisearch/meilisearch-java/pull/385

**Comment by brunoocasali** [comment]
@adolfo-trocoli do you know if we can reduce more code with this change you have in mind?
