### ISSUE TITLE
The total number of paginated results is wrong

### ISSUE THREAD

**Issue by Anbool** [meilisearch/meilisearch-java#390]
**Description**
The total number of paginated results is wrong

**Expected behavior**
The total number of correct query results returned.

**Current behavior**
Hello, it took me a few days to replace our ES with meilisearch. At present, everything is well tested, but we use the JAVA SDK provided by meilisearch. By querying the results returned by meilisearch, we found that there is a problem with the statistical number of paginated query results. Each last page of 's is automatically incremented by 1 offset. This will cause the total number of query results to be more than 20 results!
**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
- OS: CentOS 8
- Meilisearch version: 0.27.1
- meilisearch-java version: 0.7.2

**Comment by oluademola** [comment]
Hello @Anbool 👋

I am glad you made the switch to Meilisearch 🎉

It's not entirely clear to me what you are trying to do and how you are doing the pagination but my understanding is that the Java SDK doesn't handle pagination. Could you please provide additional information on what you are trying to do?

Many thanks 🙂

**Comment by Anbool** [comment]
@oluademola If meilisearch doesn't handle pagination, then what should I do? If every query returns all query results, that seems unlikely, right?

**Comment by Anbool** [comment]
I now use two parameters offset and limit for paging, offset is used to calculate the offset, limit is a fixed value: 20

**Comment by Anbool** [comment]
Our app and website use autoload to load the next page, as described in this document: https://github.com/meilisearch/documentation/issues/561
But we are using a similar loading method with DuckDuckGo, DuckDuckGo needs to click to load the next page, we are loading the next page automatically.
