### ISSUE TITLE
The results of the query through the JAVA SDK are inconsistent with the results of the meilisearch api query.

### ISSUE THREAD

**Issue by Anbool** [meilisearch/meilisearch-java#391]
**Description**
The results of the query through the JAVA SDK are inconsistent with the results of the meilisearch api query.

**Expected behavior**
The results of the query through the JAVA SDK are consistent with the results of the meilisearch api query.

**Current behavior**
I query keyword: X through JAVA SDK, which is inconsistent with the API query keyword: X provided by meilisearch.
The results of the query provided by the API provided by meilisearch are correct, but the query results provided by the JAVA SDK are wrong.

**Screenshots or Logs**
JAVA SDK search: X, wrong result.
![image](https://user-images.githubusercontent.com/17548648/169770758-c2ce3eb0-6c58-43fc-9f68-11ef7c4d0c5d.png)

Meilisearch search: X, the result is correct.
![image](https://user-images.githubusercontent.com/17548648/169771032-e0316ade-bdf5-42ed-8ff6-c26458533b46.png)

**Environment (please complete the following information):**
- OS: CentOS 8
- Meilisearch version: 0.27.1
- meilisearch-java version: 0.7.2

**Comment by alallema** [comment]
Hi @Anbool,
Thanks for raising this issue, I try the results of the Java SDK and compare them to the results from the `Meilisearch` API and I get the same results. Could you give me more details on what doesn't fit the type of research you are doing and maybe also a small data set to test?

**Comment by Anbool** [comment]
@alallema 
```json
[
{"id":"65283","title":"X","originlName":"X","alias":"X / x"},
{"id":"64813","title":"X特遣队：全员集结","originlName":"The Suicide Squad","alias":"新自杀小队 / 自杀特攻(港) / 自杀突击队集结(台) / 自杀小队2 / X特遣队2 / 自杀突击队2 / Suicide Squad 2"},
{"id":"49423","title":"我们是X","originlName":"We Are X","alias":"X JAPAN 的死与生(港) / We Are X: X JAPAN 重生之路(台)"},
{"id":"51925","title":"X战警：黑凤凰","originlName":"Dark Phoenix","alias":"变种特攻：黑凤凰(港) / X战警：黑凤凰传奇 / X战警：超新星 / X战警前传4 / X战警7 / X-Men: Supernova / X-Men: Dark Phoenix"},
{"id":"52608","title":"嫌疑人X的献身","originlName":"용의자 X","alias":"嫌疑人X / 嫌疑犯X(台) / Perfect Number / Suspect X"},
{"id":"64468","title":"XX","originlName":"엑스엑스","alias":"蓝月亮 / 블루문 / Blue Moon"},
{"id":"51437","title":"极限特工","originlName":"xXx","alias":"3X反恐暴族(港)/限制级战警(台)/限制级特工"},
{"id":"51434","title":"极限特工2","originlName":"xXx: State of the Union","alias":"3X之特种叛变(港) / 限制级战警2：极限公国(台) / 极限战士 / xXx 2: The Next Level"},
{"id":"57141","title":"极限特工3：终极回归","originlName":"xXx: Return of Xander Cage","alias":"极限特工：终极回归 / 3X反恐暴族：重火力回归(港) / 限制级战警3: 重返极限(台) / 极限特工3 / Xander Returns"},
{"id":"62499","title":"四月一日灵异事件簿","originlName":"xxxHOLiC","alias":"四月一日灵异记事簿/次元魔女"},
{"id":"62502","title":"四月一日灵异事件簿·继","originlName":"XXX ホリック","alias":"四月一日灵异记事簿2/次元魔女2/四月一日君"}
]
```
Note line 2, which is the result I want to query, the meilisearch api puts the result from line 2 first, no problem. But the JAVA SDK only returns the results of lines 7-12, and only 6 results are returned.

**Comment by Anbool** [comment]
I didn't do any special configuration, everything is configured according to the method recommended by meilisearch, but I think the only possibility of this problem seems to be related to this issue: https://github.com/meilisearch/meilisearch-java/issues/390
It seems that this result appears because of the paging problem. I have adjusted the paging, because the offset of the total number of results will be +20 on the last page of the returned result each time the JAVA SDK returns, which causes the final paging result to be different. Correct, the only thing I tweaked the pagination, I think it might be for this reason.

**Comment by alallema** [comment]
There is no real pagination on the search results. However, you can indeed play with the parameters [offset](https://docs.meilisearch.com/reference/api/search.html#offset) and [limit](https://docs.meilisearch.com/reference/api/search.html#limit).
I did some tests to see if the Java SDK returns what Meilisearch returns. For example, if I used your document and I request "X" as a query I will receive 11 results like the API.
If I used the offset and limit parameters I receive the same results as the `Meilisearch` API.

**Comment by Anbool** [comment]
Can you give me a best practice for JAVA? I'm not sure why I'm getting inconsistent results. I would like to know if meilisearch does not provide pagination, what should the business do? Return all query results every time?

**Comment by Anbool** [comment]
It doesn't seem that hard to do this, but I would like to know that when our users query keywords, our search page will return the total number of results for the query to the keyword, due to the JAVA SDK offset in the last page of query results It will increase by 20 uniformly. How can I get the value of the total number of query results correctly?

**Comment by Anbool** [comment]
> For example, if you want to request 10 documents per page you can do this:
> 
> ```
>       SearchResult searchResult = client.index("myIndex").search(new SearchRequest("X").setLimit(100));
>       int nbHits = searchResult.getNbHits();
> 
>       for (int i = 0; i < nbHits; i = i + 10) {
>         SearchRequest searchRequest = new SearchRequest("X")
>           .setOffset(i)
>           .setLimit(10);
>         System.out.println(client.index("myIndex").search(searchRequest));
>       }
> ```
> 
> With your document I had a result that looks like this: ![Screenshot 2022-05-23 at 15 53 36](https://user-images.githubusercontent.com/16155041/169835046-52cfaf08-8e25-412d-8744-bc781df90b79.png) Is that what you want?

This result is correct

**Comment by alallema** [comment]
Great! I closed this issue then.
