### ISSUE TITLE
Find a better way to construct the typoTolerance settings 

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-java#393]
In this PR #371 we introduce the `TypoTolerance` class. Unfortunately as per [this comment section](https://github.com/meilisearch/meilisearch-java/pull/371/files#r864855579) we did not found a better way than the following to encode in JSON.

```java
  public JSONObject toJson() {
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("enabled", this.enabled);
        jsonObject.put("minWordSizeForTypos", this.minWordSizeForTypos);
        jsonObject.put("disableOnWords", this.disableOnWords);
        jsonObject.put("disableOnAttributes", this.disableOnAttributes);
        return jsonObject;
    }
```

Doing `gson.toJson(this);` resolves in the following decoding: 
```
"typoTolerance":"{\"enabled\":true,\"disableOnWords\":[\"and\"],\"disableOnAttributes\":[\"title\"]}","displayedAttributes":["*"]}
```
which is not what we are looking for.

Is there a better way to encode in JSON without having to overload the `toJson` method?

**Comment by alallema** [comment]
This issue has been resolved #425
