### ISSUE TITLE
Implement a method to delete a batch of documents

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-java#42]
The implementation for [this route](https://docs.meilisearch.com/references/documents.html#delete-documents) letting the user delete a batch of documents by providing a list of document ids is missing from the SDK.

Method names should be explicit, for making the difference obvious, like `deleteAllDocuments()` and `deleteDocuments([...])` (these are the method names used in other MeiliSearch SDKs)

- [ ] Implement the method for deleting a batch of documents as `deleteDocuments([...])`
- [ ] Rename the `deleteDocuments` method (which currently deletes all documents) to `deleteAllDocuments()`
- [ ] Add tests for `deleteDocuments()`

**Comment by curquiza** [comment]
I would not say the renaming is optional as it could lead to total removal if someone use deleteDocuments() without any parameter. This behavior is not obvious for everyone from my POV, especially if the users think using the batch-delete method 🙂

**Comment by eskombro** [comment]
@curquiza Updated, thanks !

**Comment by cardinalion** [comment]
Do you mean change deleteList to deleteDocuments and change deleteDocuments to deleteAllDocuments?

**Comment by eskombro** [comment]
> Do you mean change deleteList to deleteDocuments and change deleteDocuments to deleteAllDocuments?

Hey @cardinalion !

`deleteList()` doesn't exist anymore!
Change `deleteDocuments()` to `deleteAllDocuments()`
And implement `deleteDocuments[...])`

**Comment by cardinalion** [comment]
@eskombro Sorry, I'm pretty new to this project. (Randomly came here) I'm asking because I'm not sure about the input parameters. Are you trying to pass an array of uids or identifiers?

**Comment by eskombro** [comment]
No problem @cardinalion , just thought for some reason that you migth have seen the `deleteList` method that was in the code before!

Indeed, MeiliSearch is expecting to receive a list of Ids (the data type must correspond to the primaryKey data type (it can be an array of ints or an array of strings)

**Comment by widlok** [comment]
Hi @eskombro , i submited PR for this issue - #44. First thing on master branch it seems like tests do not compile after last merge, i fixed the errors in the PR so code compiles.

Is it possible to run tests locally? I'm running into issue during **Java CI with Gradle / build (pull_request)** with an error

> com.meilisearch.integration.DocumentsTest > testDeleteDocuments() FAILED
     java.lang.IllegalStateException at DocumentsTest.java:218

I would like to debug it locally and find reason for that error.

**Comment by eskombro** [comment]
Hi @widlok !

The CI test for integration are tagged as `"integration"` so they aren't run by normal check, but you can run them easily with this tag.

Try `gradle cleanTest integrationTest`

**Comment by eskombro** [comment]
This has been done by @widlok in #44 

Closing!
Thanks :)
