### ISSUE TITLE
Search Json deserialize error

### ISSUE THREAD

**Issue by russleung44** [meilisearch/meilisearch-java#454]
**Description**
Use demo data to seach throw MeiliSearchApiException
{error=APIError{message='Json deserialize error: invalid type: string "[Ljava.lang.String;@351d00c0", expected a sequence at line 1 column 65
', code='bad_request', type='invalid_request', link='https://docs.meilisearch.com/errors#bad_request'}}

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/56534185/195538840-711e8b44-e0cb-42f2-968c-26e7bef4d76f.png)

**Environment (please complete the following information):**
- OS: [e.g. Win10]
- Meilisearch version: [e.g. v.0.29.0]
- meilisearch-java version: [e.g v0.7.2]

**Comment by alallema** [comment]
Hi @russleung44,
This is normal, unfortunately, the java SDK is only compatible up to the version `v0.27.0` of Meilisearch. You can check it on the [release Changelog](https://github.com/meilisearch/meilisearch-java/releases).
A refactor is in progress, I hope it will be available soon.
