### ISSUE TITLE
Please update README to show the compatible between different versions of SDK & server side

### ISSUE THREAD

**Issue by zhengcan** [meilisearch/meilisearch-java#500]
Yesterday, I've tried to use v0.8.0 SDK to connect v0.30.1 server side.
It reports several strange errors....

**Comment by alallema** [comment]
Hi @zhengcan,
It's normal this SDK is being updated. You can read on the [README](https://github.com/meilisearch/meilisearch-java#-compatibility-with-meilisearch) that it is currently compatible with Meilisearch v0.27.0.
The update should arrive soon. Sorry for the convenience.
