### ISSUE TITLE
Improve test `testClientGetTasks`

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-java#501]
This test `src/test/java/com/meilisearch/integration/TasksTest.java:54` is looping over all the available tasks in the instance, which makes my development harder! 

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/4116980/207157269-317fd4cf-639e-46fc-ab24-10307089d374.png">

The ideal would just check one or two tests and look specifically to a value or a particular assertion, not to look into every task and do the assertions in all of them.

**Comment by oraliahdz** [comment]
Hi @brunoocasali, I'm looking at the code for this issue, but I see that there are  already other tasks with limits that take place, so what if in testClientGetTasks rather than a For Loop, we test 1 randomly selected task only. Do you think that approach would work?

**Comment by alallema** [comment]
Hi @oraliahdz,
> we test 1 randomly selected task only. Do you think that approach would work?

I'm not sure what you mean by "randomly", but yes the goal is only to remove the for loop and test 1 or 2 tasks instead

**Comment by oraliahdz** [comment]
Yes, select a Task with a random index (as in Math.random) and validate that task. I mean, we could also just evaluate the first Task rather than the whole Array, but the following test already test the first two tasks, so It might be repetitive.

**Comment by alallema** [comment]
>  I mean, we could also just evaluate the first Task rather than the whole Array

This is exactly what should be done, I think the use of Math.random might be overkill.

> but the following test already test the first two tasks, so It might be repetitive.

I am not sure I remember the test you are talking about but the important thing to check is that it is not the same query with the same parameters if the query is different then we keep the test otherwise it can be deleted

Do not hesitate to contact us if you need more details

**Comment by oraliahdz** [comment]
I could not get rid of the for each loop, since I was getting Array Index Out Of Bounds Exception so I just made it stop after the first iteration. Please let me know if that works.
