### ISSUE TITLE
Implement overload method on `getRawIndexes` for accepting query parameters

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-java#521]
**Description**
The method `getRawIndexes()` is currently available in this SDK and allows the user to retrieve the results of indexes as `String`:
```
    public String getRawIndexes() throws MeilisearchException
```
But this method does not accept query parameters as `getIndexes` method:
```
    public Results<Index> getIndexes(IndexesQuery param) throws MeilisearchException
```

**Basic example**
The `getRawIndexes` should be overloaded to accept query parameters as:
```
    public String getRawIndexes(IndexesQuery param) throws MeilisearchException
```

This implementation should be done in the `Client` file and the `IndexesHandler` files too.

**Comment by oraliahdz** [comment]
Hi, I would like to help. Is this still open?

**Comment by alallema** [comment]
Hi @oraliahdz,
Yes, it's still open, so don't hesitate 😊

**Comment by oraliahdz** [comment]
Hi, @alallema I might have underestimated how different is to work on a Java app vs a Java library. Any resources you might recommend me?

**Comment by alallema** [comment]
Hi @oraliahdz,
Of course but depending on what you want exactly there is plenty of ressources
