### ISSUE TITLE
Correction of naming methods related to Ranking Rules

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-java#525]
**Description**
All three methods related to Ranking Rules Setting have a typo and missing the s to rules

**To do**
- Rename `getRankingRuleSettings` to `getRankingRulesSettings`
- Rename `udpateRankingRuleSettings` to `udpateRankingRulesSettings`
- Rename `resetRankingRuleSettings` to `resetRankingRulesSettings`
- Update code-sample with the new names
- Update tests with the new names

**Comment by ghousek1** [comment]
hi @alallema renamed the methods in source code along with test case names and variable names in test cases . please let me know if any change is required
