### ISSUE TITLE
Migrate search from GET to POST

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-java#54]
Serach should use the POST `/indexes/:uid/search` route instead of GET `/indexes/:uid/search`

See https://github.com/meilisearch/integration-guides/issues/37

This issue is ready to be implemented, if you need any precision or help, do not hesitate to contact me! :)

**Comment by mayralgr** [comment]
Hi @eskombro can I work on this? Is there any other information I need? 
Thank you!

**Comment by eskombro** [comment]
Hello @mayralgr 

Of course, thank you very much! All the information is detailed in the issue linked in the description ([this one](https://github.com/meilisearch/integration-guides/issues/37)), and you can use other SDK's as an inspiration source, because this has been implemented in all of them!

And of course, if you have any doubts or need any help/support, you can come here and we'll try to help :)

**Comment by mayralgr** [comment]
HI @eskombro I have made some changes, nevertheless I am not sure is all it should be done. Also, I believe I have to write some tests? Could you clarify this for me, please 😄
