### ISSUE TITLE
Http client gets initialized with GsonJsonHandler instead of configured customJsonHandler

### ISSUE THREAD

**Issue by gpor0** [meilisearch/meilisearch-java#550]
**Description**
I am not sure if this is by design but jsonHandler gets initialized to GsonJsonHandler in Config class constructor. I would like to use custom Json Handler but I am unable to use it since httpClient is already initialized with Gson and does not get updated after setJsonHandler() function call.

**Expected behavior**
To add JsonHandler to Config constructor so the httpClient gets initialized properly.

**Current behavior**
What happened.

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment:**
- OS: [OSX]
- meilisearch-java version: [0.10.0]

**Comment by Subby** [comment]
I've come across the same issue.

I'm using Spring Boot and setup a bean with the Meilisearch `Client`:
```
    @Bean
    public Client meilisearchClient() {
        var config = new Config(host, key);
        config.setJsonHandler(new JacksonJsonHandler());
        return new Client(config);
    }
```

However, I can see that the Gson handler is being used when an error occurs:
```
java.lang.RuntimeException: com.google.gson.JsonIOException: Failed making field 'java.net.Proxy#type' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
```

**Comment by gpor0** [comment]
It is probably there to separate internal parser needed for Meilisearch from the payload parser used for indexing. 

But still, I don't see a reason why we shouldn't have an option to use the Json parser we already have in application (for example JsonB or Jackson) and not depend on additional external library (gson) which needs to be in this case in the app deployment.

**Comment by alallema** [comment]
Hi @gpor0,
Thank you for raising this issue! 
>But still, I don't see a reason why we shouldn't have an option to use the Json parser we already have in application (for example JsonB or Jackson) and not depend on additional external library (gson) which needs to be in this case in the app deployment.

You are absolutely right that would be the best option, though, and it was a discussion, but it seemed simpler to propose a default library, in this case, `Gson` for the user and for the maintenance of the SDK even if, indeed, it adds an external library during the deployment.
You can check this issue #253 and this PR #432 for more context.

It will be a great improvement to offer this solution to remove the need to import and use a default library. I will create an issue about this unless you prefer to create it unfortunately we will not have the time to implement it and this will be left to the community also, it will be impossible for us to maintain more than one library which will remain the default library
