### ISSUE TITLE
Create an enum to handle the Task Status

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-java#556]
**Description**
Currently, the Task status in `TaskInfo` is a `String`
```java
public class TaskInfo {
    protected String status = "";
    protected int taskUid = 0;
    protected String indexUid = "";
    protected String type = null;
    protected Date enqueuedAt = null;

    public TaskInfo() {}
}
```
But the status could only be one of this value: `enqueued`, `processing`, `succeeded`, `failed`, `canceled`.
It could be great to create an [enum](https://www.baeldung.com/a-guide-to-java-enums) to handle this like in the [.NET repository](https://github.com/meilisearch/meilisearch-dotnet/blob/0acea9667cbdec92e04c197422b4c8d1f88a15e5/src/Meilisearch/TaskInfo.cs#L96).

**Comment by TheClerici** [comment]
I can work on it!

**Comment by alallema** [comment]
Hi @TheClerici,
Of course 😃
