### ISSUE TITLE
Apply `SearchRequest` builder changes to code-sample

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-java#560]
Following the PR #543, now the `SearchRequest` could be used with a `builder`:
```
SearchRequest.builder()
    .q("")
    .offset(10)
    .limit(200)
    .cropLength(5)
    .cropMarker("…")
    .build();
```
For consistency, all code samples must be modified using the builder method instead of:
```
new SearchRequest("")
    .setOffset(10)
    .setLimit(200)
    .setCropLength(5)
    .setCropMarker("…");
```

Or any other variants...

**Comment by PotatoDoge** [comment]
Could you assign this to me, please?

**Comment by brunoocasali** [comment]
Hi @PotatoDoge 

We prefer not assigning external people to our issues.

Why? People often ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix the issue.

We will accept and merge the first PR that fixes correctly and implements the issue following the contribution guidelines of the corresponding repository.

We are looking forward to your contributions. No need to wait for an assignment to start! 👍

**Comment by PotatoDoge** [comment]
what java version should I use? (in order to configure correctly my IDE)

**Comment by alallema** [comment]
Hi @PotatoDoge,
I would recommend working with Java 8

**Comment by PotatoDoge** [comment]
just to be clear, what must be done is to change all SearchRequest instances in the project (both testing and class files) to be initialized with the builder, right?

**Comment by PotatoDoge** [comment]
Just created a pull request!! :D
