### ISSUE TITLE
org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.meilisearch.sdk.Client]: Factory method 'client' threw exception with message: okhttp3/MediaType

### ISSUE THREAD

**Issue by dh-free** [meilisearch/meilisearch-java#580]
**Description**
Using the sdk, we keep getting errors when constructing the Client object

**Expected behavior**
Hope to use it normally

**Current behavior**
The execution keeps throwing errors

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/48708512/230294982-153605c5-96cb-4607-81b0-611c7c5d014f.png)

**Environment (please complete the following information):**
- SpringBoot3.0.5
- jdk17
- meilisearch-java version: 0.11.0

**Comment by YeFei572** [comment]
I have same question, and I fixed it as follow:
```
        <!-- https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp -->
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.10.0</version>
        </dependency>
```

**Comment by brunoocasali** [comment]
Hey @dh-free and @YeFei572 does this always happen, or after a particular update (java or meilisearch)?

Also, @alallema I think it is good to introduce a CI action to test this repo with newer java versions as well :)

**Comment by YeFei572** [comment]
I just learned melisearch and code a demo based on the quick start guide in the official documentation. However, I encountered the error mentioned above. The version I used is the latest one and I haven't tried other versions.

**Comment by brunoocasali** [comment]
Cool, thanks for the information! I'll try to submit the new GH action just to ensure we support your Java version.
