### ISSUE TITLE
Add support for the new stats from numerical facets like `min`, `max`

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-java#592]
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, feel free to add any clarification and instruction about this issue.

Sorry if this is already partially/completely implemented, feel free to let me know about the state of this issue in the repo.

Related to https://github.com/meilisearch/integration-guides/issues/251

----

Related to:
- issue: https://github.com/meilisearch/meilisearch/issues/3426
- spec: https://github.com/meilisearch/specifications/pull/224

Make sure the SDK has a proper way to access the new `facetStats` information. 
And there is **no need to add a new test use case for this feature**. Only add a few assertions in the existing tests that use facets. If they exist, it will be enough.

**Comment by sumitdethe27** [comment]
Hey @brunoocasali  ,
Is this issue available, I would like to work on it.

**Comment by sumitdethe27** [comment]
Hey ,
Is this issue available, I would like to work on it.

**Comment by alallema** [comment]
Hi @sumitdethe27,
Yes, this issue is still available, so don't hesitate to get started!
