### ISSUE TITLE
Using Meilisearch-java client in an Android App

### ISSUE THREAD

**Issue by AmirOsman2020** [meilisearch/meilisearch-java#616]
Hello, I want to implement search functionality on my android app using Meilisearch and I'm wondering if the Java client can be implemented in an Android app or should I use the JavaScript client in my nodejs API and get the search results using my rest API?

**Comment by brunoocasali** [comment]
Hi @AmirOsman2020!

Yes, you can, but it is up to you if you want to go for the nodejs direction is also acceptable. The good thing about using the SDK directly is that you can save some `ms` from the extra roundtrip you would have been doing if you went for the nodejs version.


Thanks for using Meilisearch ❤️

**Comment by AmirOsman2020** [comment]
Great, thanks for the clarification but I'm a little bit concerned about security, if I connected to Meilisearch directly from my app using the Meilisearch-java (Client client = new Client(new Config("http://localhost:7700", "masterKey"));) then I'll be exposing the URL and the MasterKey knowing that android apps (APKs) can be easily reversed engineered.

**Comment by brunoocasali** [comment]
You should not use the masterKey in the SDK, even in the backend ones, the masterKey should be used only for creating other keys with fewer permissions!

**Comment by alallema** [comment]
Thanks, @brunoocasali for answering this ❤️ !
HI @AmirOsman2020,
For more information about key usage, you can check the [documentation about it](https://www.meilisearch.com/docs/learn/security/master_api_keys).
