### ISSUE TITLE
Possible unintended definition of BasicResponse.create

### ISSUE THREAD

**Issue by jrhenderson1988** [meilisearch/meilisearch-java#642]
I noticed when re-writing the tests in [this PR](https://github.com/meilisearch/meilisearch-java/pull/638) that the type signature of `BasicResponse.create` appears to conflict with the way in which it is used in one of the tests. This lead me to believe that the intention behind `BasicResponse.create` is a little different to what it is currently doing. This is best illustrated by showing some code:

```java
    public <T> HttpResponse<T> create(
            HttpResponse<T> httpResponse, Class<T> targetClass, Class<?>... parameters) {
        try {
            T content = this.jsonHandler.decode(httpResponse.getContent(), targetClass, parameters);

            return new HttpResponse<T>(
                    httpResponse.getHeaders(),
                    httpResponse.getStatusCode(),
                    httpResponse.getContent() == null ? null : content);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```

This is the code that I'm talking about. The generic parameter `T` here is the type that the _returned_ `HttpResponse` is generic over. The first argument is a `HttpResponse<T>` which suggests that whatever `T` is passed in as the type parameter to first argument, should be the exact same `T` that is returned.

If this was the intention then there would be no need for the second argument of type `Class<T>` since `T` could be inferred from whatever was passed in as the first argument.

However, the second parameter `Class<T> targetClass` is present, and presumably is there so that the caller can explicitly say what `T` should be, suggeseting that there's perhaps another type expected here (probably the return type).

This is reinforced by the associated test for this method:

```java
        String content =
                "{ \"uid\": 0, \"indexUid\": \"\", \"status\": \"\", \"type\": null, \"details\": null, \"duration\": \"\", \"enqueuedAt\": null, \"startedAt\": null, \"finishedAt\": null}";
        HttpResponse response = new HttpResponse(null, 0, content);
        HttpResponse<Task> httpResponse = basicResponse.create(response, Task.class);
```

As you can see, there's no type argument when defining `HttpResponse response = ...`. It is clear that the type that is actually constructed is `HttpResponse<String>` because the third argument of the constructor (`content`) is of type `String`. However, if we change the above test to this:

```java
        String content =
                "{ \"uid\": 0, \"indexUid\": \"\", \"status\": \"\", \"type\": null, \"details\": null, \"duration\": \"\", \"enqueuedAt\": null, \"startedAt\": null, \"finishedAt\": null}";
        HttpResponse<String> response = new HttpResponse(null, 0, content); // <--- added <String> here
        HttpResponse<Task> httpResponse = basicResponse.create(response, Task.class);
```

We get a compiler error, because the signature of `BasicResponse.create` is expecting that the returned `HttpResponse<T>` and the first argument `HttpResponse<T>` to have the same `T`, but since `String` is not the same as `Task`, it complains.

If my assumptions are correct here, and the intention of this method is to be able to take a `HttpResponse` of some type and transform it into a `HttpResponse` of some other type, then the fix for this is pretty simple. I can submit a PR to do this and you are free to accept it if it does the trick for you 😄

**Comment by jrhenderson1988** [comment]
Hi @alallema - thanks for getting back to me.

The problem that I'm trying to explain here is not really related to having to pass in a `Class<T> targetClass`. I understand that you need it in the `decode` method of Gson implementation of the `JsonHandler` interface, and I think that makes sense to do.

The issue that I am trying to raise is that this particular method, `BasicResponse.create`, is actually written in such a way that you're only allowing there to be one `T`. Where `T` is the type parameter of both the `HttpResponse<T>` passed in as the first argument, but also the type `HttpResponse<T>` return type. This type signature (using `T` in both places) tells the compiler that both the first argument and the return type have _exactly_ the same type.

However, take a look at the test (found in `BasicResponseTest.contentClass`):

```java
        String content =
                "{ \"uid\": 0, \"indexUid\": \"\", \"status\": \"\", \"type\": null, \"details\": null, \"duration\": \"\", \"enqueuedAt\": null, \"startedAt\": null, \"finishedAt\": null}";
        HttpResponse response = new HttpResponse<>(null, 0, content);
        HttpResponse<Task> httpResponse = basicResponse.create(response, Task.class);
```

We can see that `content` is of type `String`, and given that `HttpResponse` has the following class and constructor signature...

```java
@Getter
public class HttpResponse<T> {
    private final Map<String, String> headers;
    private final int statusCode;
    private final T content;

    public HttpResponse(Map<String, String> headers, int statusCode, T content) {
```

... we can see that the third argument to the constructor has a type `T`, which refers to the generic type parameter on `HttpResponse`. So, whatever type is passed into the third argument when constructing a `HttpResponse` (using this constructor), becomes the generic type of the `HttpResponse`. So, from that we can infer that the actual type of `response` in the test code above is `HttpResponse<String>` since `content` has type `String` and it is passed as the third argument to the constructor. The type argument is not provided in the test, but as you can see from the below screenshot, Intellij warns us that we're using a parameterized type without proving type arguments, and actually suggests to us to change the type to be what the actual type is (`HttpResponse<String>`).

<img width="621" alt="image" src="https://github.com/meilisearch/meilisearch-java/assets/8791010/c633228a-eddd-45fb-88f7-229613cdb999">

Following on from that, the variable `httpResponse` is declared to have a type of `HttpResponse<Task>`.

The call to `BasicResponse.create` in the above test accepts `response` which has an underlying type of `HttpResponse<String>` (though it is untyped in the actual test code and generates warnings) as the first argument, but it returns `HttpResponse<Task>`.

Since the definition of `BasicResponse.create` declares only a single `T` type argument and it is used on both the first argument and the return type, then both the first argument and the return type must be exactly the same type. But in this case, `HttpResponse<String>` (the first argument) and `HttpResponse<Task>` are actually different.

If we accept Intellij's suggestion above and we explicitly give `response` a type of `HttpResponse<String>` we get a whole load of warnings from Intellij and compiler errors, due to this inconsistency.

The way to work around this, as has been done in the test, is to remove the type arguments from `response`, which allows us to avoid the issue, but at the cost of type safety.

This is the reason for raising the issue, and my pull request aims to address this. It assumes that the first argument and the return type need not have exactly the same generic type. They can be the same, but they don't have to be. It allows us to convert/decode a `HttpResponse<String>` into a `HttpResponse<Task>`, in a type safe way.

Another potential (but more limited) solution to this could be to just change the type signature of `BasicResponse.create` to something like this:

```java
    public <T> HttpResponse<T> create(
        HttpResponse<String> httpResponse, Class<T> targetClass, Class<?>... parameters) {
```

this would allow us to decode a `HttpResponse<String>` into some other type, but it would limit the method to only accepting a `HttpResponse<String>` which is more limited.

Apologies for the very long winded response. I hope this helps to explain the problem

**Comment by alallema** [comment]
Hi @jrhenderson1988,

Thank you very much for all these explanations, it's much clearer. And yes, I understand that this modification is indeed necessary!

**Comment by jrhenderson1988** [comment]
No worries @alallema - happy to help :)
