### ISSUE TITLE
A better way to add documents in the Getting Started example?

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-java#67]
Currently, here is the way to add documents we show in the first Getting Started example:

```java
final String documents = "["
	+ "{\"book_id\": 123, \"title\": \"Pride and Prejudice\"},"
	+ "{\"book_id\": 456, \"title\": \"Le Petit Prince\"},"
	+ "{\"book_id\": 1, \"title\": \"Alice In Wonderland\"},"
	+ "{\"book_id\": 1344, \"title\": \"The Hobbit\"},"
	+ "{\"book_id\": 4, \"title\": \"Harry Potter and the Half-Blood Prince\"},"
	+ "{\"book_id\": 2, \"title\": \"The Hitchhiker\'s Guide to the Galaxy\"}"
	+ "]";
```

We would like to use, if it exists, a more friendly way to add documents that we can introduce into our Getting Started, instead of escaping double-quotes.

Maybe we could be inspired by the Stripe Java client and the `HashMap` solution, but it might also involve lots of lines, and this solution might be "heavy" too.
https://github.com/stripe/stripe-java#usage

What do you think?
Does someone know a way to make the Getting Started example more friendly? 😄

**Comment by mohitsaxenaknoldus** [comment]
@curquiza I have an idea. What if we create a Map of our items and then convert that Map to JSON. After that, we simply convert that JSON to string using `toString()` and pass it to our `addDocuments()` function.

**Comment by curquiza** [comment]
Hello @mohitsaxenaknoldus!
Feel free to open a PR, we will see if we merge it or not :) Even if we don't merge it, we can consider it as a Hacktoberfest contribution since you are helping us with trying to find an alternative solution!

**Comment by mohitsaxenaknoldus** [comment]
PR raised @curquiza : https://github.com/meilisearch/meilisearch-java/pull/223
