### ISSUE TITLE
Generic class for search results

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-java#68]
In the current state of the Java SDK, the return value of the search method is a String, which needs to be deserialized by the user after performing a search.

This SDK should provide a generic class capable of deserializing MeiliSearch results. Search method should return an instance of this object, with MeiliSearch's results already deserialized.

**Comment by djKooks** [comment]
@eskombro I think I could work on it. 

For case which returning value does not have fixed form, how do you think of returning value as `Map` object?

**Comment by eskombro** [comment]
Amazing @djKooks !

Are you talking about the "hits" field? if that's the case, I think a Map or a HashMap Are indeed the best options :)

**Comment by djKooks** [comment]
@eskombro I've create PR for this. It only includes very raw commits, just want to share whether it is the one you're intending. Please check 🙏
