### ISSUE TITLE
Setup custom exceptions

### ISSUE THREAD

**Issue by djKooks** [meilisearch/meilisearch-java#7]
Setup custom exceptions

**Comment by eskombro** [comment]
[This discussion](https://github.com/meilisearch/integration-guides/issues/19) will be very useful to give Java SDK's custom exceptions some coherence with other SDKs error handlers for MeiliSearch, which would be ideal (but of course not mandatory if there are some Java specifics that go against it)!

**Comment by eskombro** [comment]
Needs #29

**Comment by eskombro** [comment]
#29 is merged, This issue can be done now! 🎉

**Comment by eskombro** [comment]
I will start working on this issue since it seems very important to have custom exceptions as soon as possible !
