### ISSUE TITLE
Gradle build fails: impossible to deploy

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-java#704]
As you can see here, it's currently impossible to deploy the new package version because gradle build is failing

https://github.com/meilisearch/meilisearch-java/actions/runs/7555131703

<img width="1156" alt="Capture d’écran 2024-01-17 à 12 46 51" src="https://github.com/meilisearch/meilisearch-java/assets/20380692/562b8d7f-c269-4fd2-9062-685c67e05119">

Any help from community will be welcome 🙏

**Comment by brunoocasali** [comment]
Fixed! #708 

https://central.sonatype.com/artifact/com.meilisearch.sdk/meilisearch-java/overview
