### ISSUE TITLE
Support for Java modularity

### ISSUE THREAD

**Issue by AlphaFoxz** [meilisearch/meilisearch-java#705]
**Description**
Hello, I am currently integrating meilisearch-java into my development work, but I've encountered an issue where it does not support Java's modular system. Additionally, my attempts to use some plugins for conversion have failed. I was wondering if there are any plans from the official side to support modularity?

**Comment by curquiza** [comment]
Hello @AlphaFoxz 

Thanks for the suggestion

We don't know this modularity concept. What modularity would bring to our library? How could it improve the user experience or the maintainer experience?
What are the drawbacks?

Also, you have to know we support Javai 8 so far, so maybe it's not compatible with modularity
Java 8 is old, so we might consider not supporting it anymore, but it's a discussion for another issue 😇

**Comment by AlphaFoxz** [comment]
Okay, thx your reply @curquiza

My description was not clear enough before. When I writing a springboot3-meilisearch-starter, there is a problem at `module-info.java` when exec `gradle build`.
```java
module starter.meilisearch {
    requires meilisearch.java;
             ^ no module named 'meilisearch.java'
    requires others ...
}
```
Now I know it won't be modular anytime soon. And I just need remove `module-info.java`. it's not a big problem.
