### ISSUE TITLE
Improve SDK automated documentation [javadoc]

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-java#71]
`meilisearch-java` uses [`javadoc`](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html) as a documentation generator, which is based on comments on the code. There are several classes, methods, and attributes that are very useful for developers who use our SDK that have no comment, and therefore no automated documentation.

Several warnings are shown when your build includes the task javadoc. It would be interesting to add some documentation to the most important classes and methods, and to suppress the warnings of those who do not need to be documented.

This is a good first issue to understand the project, and how it is plugged to MeiliSearch

Note: This doesn't need to be solved all in one single PR, any partial contribution would be appreciated.

____
I would say that the most important is to add the appropriate comments to the main classes: `Client`, `Index`, `Search`, `SearchRequest` and it's main methods with a short description of the method, params, return values and Exceptions

As an example:

```java
/**
 * Wait for a pending update to be processed
 *
 * @param updateId ID of the index update
 * @param timeoutInMs number of milliseconds before throwing an Exception
 * @param intervalInMs number of milliseconds before requesting the status again
 * @throws Exception if timeout is reached
 */
public void waitForPendingUpdate(int updateId, int timeoutInMs, int intervalInMs) throws Exception {
	// ...
}
```

**Comment by JacobSherrod** [comment]
do you have any main focal points regarding documentation for this project?

**Comment by eskombro** [comment]
Hey @JacobSherrod 

Not really. We focus on our [official docs](https://docs.meilisearch.com/) for now and haven't actually created a real strategy of in-code documentation. As the SDk was done by adding up many contributions, there is no regularity, some things are very well documented and some, well, not at all.

I would say that the most important is to add the appropriate comments to the main classes : `Client`, `Index`, `Search`, `SearchRequest` and it's main methods with a short description of the method, params, return values and Exceptios

**Comment by eskombro** [comment]
I updated the description

**Comment by JacobSherrod** [comment]
Cool. I can take a look at those and see what all I can contribute. Thank you
