### ISSUE TITLE
SearchResult is missing totalPages field

### ISSUE THREAD

**Issue by matthiasmoke** [meilisearch/meilisearch-java#711]
**Description**
Hi, it seems that the SearchResult class does not contain the totalPages of the Meilisearch [search result](https://www.meilisearch.com/docs/reference/api/search#response)
At least I could not find it anywhere 😅 
We would need this field in order to display the total pages in our frontend.

**Expected state**
The totalPages can be retrieved via a getter on the SearchResult

**Current state**
Means to retrieve the totalPages are not present, neither on the SearchResult class nor on the Searchable interface.

**Environment (please complete the following information):**
- Meilisearch version: 1.2
- meilisearch-java version: 0.11.5

**Comment by curquiza** [comment]
Hello @matthiasmoke 

thanks for the report

Any contribution is welcomed ❤️

**Comment by matthiasmoke** [comment]
Update from my side. I found it after all 😄 
It's contained in the `SearchResultPaginated` type. Will close the issue
