### ISSUE TITLE
Remove warnings from Json Handling classes 

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-java#72]
`JacksonJsonHandlerTest.java` and `GsonJsonHandlerTest.java` generate varargs warnings 

<img width="763" alt="Screenshot 2020-12-02 at 15 34 56" src="https://user-images.githubusercontent.com/10339833/100891405-83d06980-34b9-11eb-9f9c-3f01892bbb32.png">

**Comment by luis-valdez** [comment]
I'll start working in this issue if nobody is currently working on it :).

**Comment by eskombro** [comment]
Nobody is on it, so really appreciated! 👍🏽
