### ISSUE TITLE
invalid_search_attributes_to_highlight

### ISSUE THREAD

**Issue by webeasymail** [meilisearch/meilisearch-java#762]
**Description**

`       

 
        <dependency>
            <groupId>com.meilisearch.sdk</groupId>
            <artifactId>meilisearch-java</artifactId>
            <version>0.13.0</version>
        </dependency>

        
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.1.1</version>
        </dependency>`

`

package search;

import com.meilisearch.sdk.Client;
import com.meilisearch.sdk.Config;
import com.meilisearch.sdk.Index;
import com.meilisearch.sdk.SearchRequest;
import com.meilisearch.sdk.model.SearchResult;
import com.meilisearch.sdk.model.Searchable;
import com.meilisearch.sdk.model.Settings;

import java.util.Map;

public class MeiliSearchExample {

    public static void main(String[] args) throws Exception {

        Config config = new Config("http://localhost:7700/", "MGPxHFcFj9wxgIDmm4bwG5xT2PRuCoo7t_kXm26O0ug");

        // 初始化MeiliSearch客户端
        Client client = new Client(config);

        // 创建索引
        String indexName = "products";
        Index index = client.index(indexName);

        // 设置权重
        Settings settings = new Settings();
        settings.setSearchableAttributes(
            new String[] {"name", "tagline", "companyName", "description"}
        );
        settings.setRankingRules(
            // words, typo, sort, proximity, attribute, exactness and custom ranking rules
            new String[] {"words", "typo", "proximity", "attribute", "exactness", "sort"}
        );

        index.updateSettings(settings);

        // 插入文档
        String[] documents = new String[]{
            "{\"id\":7034, \"code\":\"aishu-anydata-fw2\", \"name\":\"AISHU爱数-AnyDATA Framework 2\", \"tagline\":\"AGI赋能的领域认知智能框架\", \"description\":\"产品功能：\\n图分析\\n直观形象的展示实体以及之间的关联关系\\n自由定制多种可视化元素，直观呈现业务关联\", \"companyName\":\"上海爱数信息技术股份有限公司\"}",
            "{\"id\":11114, \"code\":\"shangji-dmp-cloud\", \"name\":\"商基DMP云数据平台\", \"tagline\":\"基于云应用的数据分析应用平台。\", \"description\":\"DMP将企业分散的第一、第三方数据进行整合纳入统一的技术平台，并对这些数据进行标准化和细分处理。\", \"companyName\":\"广东商基网络科技有限公司\"}"
        };
        for(String doc:documents){
            index.addDocuments(doc);
        }

        // 搜索并获取高亮
        SearchRequest searchRequest = new SearchRequest("智能");
        searchRequest.setAttributesToHighlight(new String[]{"name", "description", "tagline"});
        searchRequest.setAttributesToCrop(new String[]{"description"});
        searchRequest.setCropLength(50);

        Searchable search = index.search(searchRequest);

        // 打印搜索结果和高亮信息
        for (Map<String, Object> hit : search.getHits()) {
            System.out.println(hit);
            System.out.println("ID: " + hit.get("id"));
            System.out.println("Name: " + hit.get("_formatted.name"));
            System.out.println("Description: " + hit.get("_formatted.description"));
            System.out.println("Tagline: " + hit.get("_formatted.tagline"));
            System.out.println();
        }
    }
}

`

**Screenshots or Logs**
`
Exception in thread "main" Meilisearch ApiException: {Error=APIError: {message='Invalid value type at `.attributesToHighlight`: expected an array, but found a string: `"[Ljava.lang.String;@1018bde2"`', code='invalid_search_attributes_to_highlight', type='invalid_request', link='https://docs.meilisearch.com/errors#invalid_search_attributes_to_highlight'}}
	at com.meilisearch.sdk.HttpClient.post(HttpClient.java:101)
	at com.meilisearch.sdk.Search.rawSearch(Search.java:49)
	at com.meilisearch.sdk.Search.search(Search.java:76)
	at com.meilisearch.sdk.Index.search(Index.java:444)
	at search.MeiliSearchExample.main(MeiliSearchExample.java:54)
`

**Environment (please complete the following information):**
- OS: Windows
- Meilisearch version: v1.9.0
- meilisearch-java version: v0.13.0

`
Config file path:       "none"
Database path:          "./data.ms"
Server listening on:    "http://localhost:7700"
Environment:            "development"
Commit SHA:             "0df84bbba7db46680e83843dd6454257161a282f"
Commit date:            "2024-06-27T12:47:08Z"
Package version:        "1.9.0"
`

**Comment by curquiza** [comment]
Hello @webeasymail 

Sorry for the inconvenient
I have to say I'm a little bit surprised. We have a lot of tests in our test suite for this, I don't know understand why Meilisearch returns the error
- https://github.com/meilisearch/meilisearch-java/blob/main/src/test/java/com/meilisearch/integration/SearchTest.java
- https://github.com/meilisearch/meilisearch-java/blob/main/src/test/java/com/meilisearch/sdk/SearchRequestTest.java

**Comment by ErrorProne** [comment]
I just stumbled upon the same problem. For me I had to import the JSON library `implementation("org.json:json:20240303")` meiliseach uses. 
Instead some other library, which defined the same namespace, was picked up which lead to the same behavior.

@webeasymail maybe it is the same for you?
