### ISSUE TITLE
Implement the method update documents routes

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-java#79]
There is no method to update documents in this package.
Here are the docs about `PUT /indexes/:uid/documents`: https://docs.meilisearch.com/references/documents.html#add-or-update-documents

- [ ] Add it in the code. You can be inspired by [`addDocuments` method](https://github.com/meilisearch/meilisearch-java/blob/b35a9bd3b633f334590a713a4d26fc9c4a9d0f7c/src/main/java/com/meilisearch/sdk/Index.java#L88-L97). But not completely because there is a missing parameter until this issue is fixed (https://github.com/meilisearch/meilisearch-java/issues/78). `updateDocuments` should also have this optional paramter.
- [ ] Add tests.

**Comment by JohanDelValleV** [comment]
Hello I'm interested in contributing and working on this issue

**Comment by curquiza** [comment]
Hello @JohanDelValleV!

Thanks a lot! I assign you!😁
