### ISSUE TITLE
updateIndex method should return an Index instance

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-java#80]
To be consistent with `createIndex` and `getIndex`, the method `updateIndex` should return an `Index` instance. This method should update the `primaryKey` attribute of the `Index` instance with the information returned by MeiliSearch.

- [ ] Update the code base
- [ ] Add tests

EDIT: this PR (https://github.com/meilisearch/meilisearch-java/pull/74) should have been merged before.

**Comment by luis-valdez** [comment]
Hello @curquiza, I would like to start working in this issue.
Is there more information that I need?

**Comment by curquiza** [comment]
Hello @luis-valdez!
Thank you very much! However, I would rather this PR (https://github.com/meilisearch/meilisearch-java/pull/74) be merged before you start this issue. That's my fault, I updated the description to be clearer.

I don't know what kind of information I can add, but if you need any, don't hesitate to ask 😄

**Comment by luis-valdez** [comment]
Oh I see! I'm looking for a `Good first issue` to work on.
So in the mean time, I'll  pick up another one. Thank you :D!

**Comment by eskombro** [comment]
Hi @luis-valdez 

It would be totally ok to start this issue now. All the previous PR and changes have been merged into master> So if you still want to work on this, it would be great! :)

**Comment by luis-valdez** [comment]
Awesome, if I have any questions I'll let you know :)

**Comment by luis-valdez** [comment]
Hello, this is how I modified the method `updateIndex`:
```java
	public Index updateIndex(String uid, String primaryKey) throws Exception {
		Index index = gson.fromJson(this.indexesHandler.updatePrimaryKey(uid, primaryKey), Index.class);
		index.setConfig(this.config);
		return index;
	}
```
Regarding the tests it's already passing the integration tests including `testUpdateIndexPrimaryKey()`.

Looking at `createIndex` I figured out it should include a test like: `testUpdateIndexPrimaryKeyIfIndexDoesNotExists()`.
Is that correct? What other tests should be convenient to include?

**Comment by eskombro** [comment]
Hi @luis-valdez 

1. The test you are suggesting seems to be a nice addition! 
    `testUpdateIndexPrimaryKeyIfIndexDoesNotExists`
2. Your updated version of `updateIndex` looks good to me

If the test is also modified in a way where we can be sure that this method is effectively returning an Index instance, this seems to be enough for me :)

**Comment by curquiza** [comment]
Sorry I don't know perfectly this package, so I don't know if the `setConfig` does what I'm going to ask:
don't forget to update the `primaryKey` attribute of the `Index` object before returning it.

**Comment by luis-valdez** [comment]
> 1. The test you are suggesting seems to be a nice addition!
>    `testUpdateIndexPrimaryKeyIfIndexDoesNotExists`
>    From my POV, trying to update the primary key of an inexistent index \should throw a MeiliSearchApiException, what do you think?
>

Yes I totally agree.
> 2. Your updated version of `updateIndex` looks good to me
> 
> If the test is also modified in a way where we can be sure that this method is effectively returning an Index instance, this seems to be enough for me :)
>

For assuring that we're returning an Index instance I was thinking in this implementation:
```java
	@Test
	public void testUpdateIndexPrimaryKey() throws Exception {
		String indexUid = "UpdateIndexPrimaryKey";
		Index index = client.createIndex(indexUid);
		assertEquals(index.getUid(), indexUid);
		assertNull(index.getPrimaryKey());
		Index returnIndex = client.updateIndex(indexUid, this.primaryKey); //saving the return value
		assertTrue(returnIndex instanceof Index); // make sure is an instance of Index
		index = client.getIndex(indexUid);
		assertEquals(index.getUid(), indexUid);
		assertEquals(index.getPrimaryKey(), this.primaryKey);
		client.deleteIndex(index.getUid());
	}
```

**Comment by luis-valdez** [comment]
> Sorry I don't know perfectly this package, so I don't know if the `setConfig` does what I'm going to ask:
> don't forget to update the `primaryKey` attribute of the `Index` object before returning it.
> 
I think that the `setConfig` does not update the primary key, but when I create the new instance of `Index`:
```java
Index index = gson.fromJson(this.indexesHandler.updatePrimaryKey(uid, primaryKey), Index.class);
```
I call the method `updatePrimaryKey` in the `IndexesHandler` class, that subsequently calls:
```java
return meilisearchHttpRequest.put(requestQuery, jsonObject.toString());
```
which I believe updates de `primaryKey`

**Comment by curquiza** [comment]
Hello @luis-valdez!

I checked directly with @eskombro! `createIndex` and `getIndex` do update the `primaryKey` attribute! So everything is ok for these methods, sorry for the confusion!

About the test you suggest, it's perfect!

Thanks again for your work!!!
