### ISSUE TITLE
Make compatible for Java >= 8

### ISSUE THREAD

**Issue by djKooks** [meilisearch/meilisearch-java#9]
Concern of supporting Java version 8 or more
- For using various features in Java 8 (stream, optional...)

**Comment by djKooks** [comment]
@eskombro hello~
How do you think of current topic?

By making compatible for Java 8 and over, we can support `stream` and `optional` and make sdk more fit to new Java module. But it will make complicate for supporting Java 7 and less.

If you want to keep current API design, it will be better to ignore this topic. If than, please close this issue 🙏

**Comment by curquiza** [comment]
Hello @djKooks!
Does this change something for the users? What would be the "Getting Started" and "Installation" sections for a user with Java 8 and Java 7 after this implementation?
When adding features we want to ensure it does not bring any complexity for the users who want to use this SDK in a simple way 🙂

**Comment by eskombro** [comment]
This is a veru interesting question and I think I would really appreciate to have different points of view on this matter on how this can affect users and what this could improve in the SDK, as @curquiza points out!

Any insights on this @djKooks , @niemannd , @luis-valdez , @AmiralBl3ndic ? :)

**Comment by djKooks** [comment]
@curquiza @eskombro thanks for comments~

> Does this change something for the users? What would be the "Getting Started" and "Installation" sections for a user with Java 8 and Java 7 after this implementation?
=> It means that we can use features in Java 8 (`Optional`, `CompletableFuture`...) to make elegant async logic. But it will block user who is still using Java 7 or less. In this case, we should write `Requirements` as `Java 1.8 or later`(you can see in Stripe Java SDK, or AWS Java SDK 2.x).

I'm suggesting this because 
- SDK is in early stage, so will not make user complicate. 
- Java 7 will soon close official support.

But if there's still lots of MeiliSearch users who is using Java 7 or less, than you can think of ignoring this.

**Comment by AmiralBl3ndic** [comment]
I agree with @djKooks on making the SDK Java 8 compliant: as he said Java 7 will soon reach the end of its official support and with MeiliSearch growing in popularity, limiting the capabilities of the SDK to old versions of Java might not be the greatest thing to do. 

As a matter of fact, I saw several Java 7 projects using `guava`'s implementation of `Optional` as a replacement for the lack of built-in `Optional` in the JDK, this is a good indicator this feature alone is a great improvement and adding it to MeiliSearch's SDK seems like the right thing to do. 

Now, doing this upgrade will obviously remove Java 7 compatibility if we use features of Java 8 within the SDK so adding a requirements `Java 1.8 or later` section to the documentation will be required.

**Comment by curquiza** [comment]
After consulting most of you, it seems to be a good option to drop the Java 7 support 😁

@djKooks what do we need to do next? Maybe should we add a small note on the README?

**Comment by djKooks** [comment]
@curquiza thanks for notice~
I'll make a draft first, and will let you know 🙏

**Comment by djKooks** [comment]
Oh, seems version has been already defined in gradle file.
https://github.com/meilisearch/meilisearch-java/blob/main/build.gradle#L21-L24

@curquiza @eskombro @AmiralBl3ndic I think it will be okay to close this.

**Comment by curquiza** [comment]
Closing then!! 🎉
