### ISSUE TITLE
update settings through SDK

### ISSUE THREAD

**Issue by ajay-a1** [meilisearch/meilisearch-java#90]
Is there any way to update setting through Java SDK?

Like for the curl request below:
$ curl \
  -X POST 'http://localhost:7700/indexes/movies/settings' \
  --data '{
      "displayedAttributes": [
          "title",
          "description",
          "poster",
          "release_date",
          "rank"
      ]
  }'

**Comment by curquiza** [comment]
Hello @ajay-a1! Thanks for your feedback, I really thought this kind of priority method was already implemented in this package, but I don't find any, my bad. I open a more detailed issue to add this.

**Comment by curquiza** [comment]
Closing this issue in favor of #93
