### ISSUE TITLE
Document the customizations

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-java#98]
If I understand well, this library provides default usage but also provides abstractions to choose and customize:
- the JSON library
- the Client
- the HTTP requests

It would be nice to add a section in the README to show with simple lines of code how to customize all of these points 🙂

**Comment by ishika22** [comment]
Hi @curquiza 
I have some previous knowledge in JSON library and HTTP requests. I can read a little about client and create a section in the README file for the same. Can you please assign this issue?

**Comment by alallema** [comment]
Hi @ishika22,
Thanks for asking, It's done.
